#  ooooooooo.   oooo                        ooooooooooooo  o8o
#  `888   `Y88. `888                        8'   888   `8  `"'
#   888   .d88'  888   .oooo.   oooo    ooo      888      oooo  ooo. .oo.  .oo.    .ooooo.
#   888ooo88P'   888  `P  )88b   `88.  .8'       888      `888  `888P"Y88bP"Y88b  d88' `88b
#   888          888   .oP"888    `88..8'        888       888   888   888   888  888ooo888
#   888          888  d8(  888     `888'         888       888   888   888   888  888    .o
#  o888o        o888o `Y888""8o     .8'         o888o     o888o o888o o888o o888o `Y8bod8P'
#                               .o..P'
#                               `Y8P'
#
name: PlayTimePNX
main: com.xardaa49.playtimepnx.Main
version: 1.0.0
api: [2.0.0]
author: xArdaa49
